export const filesSchema = {
  type: "array",
  items: {
    type: "object",
    properties: {
      fileName: { type: "string" },
      exifData: {
        type: "object",
        properties: {
          bigEndian: { type: "boolean" },
          image: {
            type: "object",
            properties: {
              Artist: { type: "string" },
              Compression: { type: "integer" },
              ThumbnailOffset: { type: "integer" },
              ThumbnailLength: { type: "integer" },
              ImageHeight: { type: "integer" },
              Make: { type: "string" },
              Orientation: { type: "integer" },
              ModifyDate: { type: "string", format: "date-time" },
              GPSInfo: { type: "integer" },
              Copyright: { type: "string" },
              YResolution: { type: "integer" },
              XResolution: { type: "integer" },
              ImageWidth: { type: "integer" },
              Model: { type: "string" },
              Software: { type: "string" },
              YCbCrPositioning: { type: "integer" },
              ExifOffset: { type: "integer" },
              ResolutionUnit: { type: "integer" },
            },
          },
          exif: {
            type: "object",
            properties: {
              "36880": { type: "string" },
              "36881": { type: "string" },
              "36882": { type: "string" },
              ApertureValue: { type: "number" },
              ExifVersion: { type: "string" },
              SceneType: { type: "string" },
              SubjectDistanceRange: { type: "integer" },
              ExposureBiasValue: { type: "number" },
              ExposureProgram: { type: "integer" },
              ColorSpace: { type: "integer" },
              MaxApertureValue: { type: "number" },
              PixelYDimension: { type: "integer" },
              BrightnessValue: { type: "number" },
              DateTimeOriginal: { type: "string", format: "date-time" },
              FlashpixVersion: { type: "string" },
              MakerNote: { type: "string" },
              SubSecTimeOriginal: { type: "string" },
              WhiteBalance: { type: "integer" },
              InteropOffset: { type: "integer" },
              CustomRendered: { type: "integer" },
              ExposureMode: { type: "integer" },
              FocalPlaneResolutionUnit: { type: "integer" },
              ExposureTime: { type: "number" },
              FocalPlaneXResolution: { type: "number" },
              Flash: { type: "integer" },
              SubSecTime: { type: "string" },
              FNumber: { type: "number" },
              ISO: { type: "integer" },
              UserComment: { type: "string" },
              PixelXDimension: { type: "integer" },
              ComponentsConfiguration: { type: "string" },
              FileSource: { type: "string" },
              FocalLengthIn35mmFormat: { type: "integer" },
              CompressedBitsPerPixel: { type: "number" },
              Sharpness: { type: "integer" },
              SubSecTimeDigitized: { type: "string" },
              DateTimeDigitized: { type: "string", format: "date-time" },
              ShutterSpeedValue: { type: "number" },
              FocalLength: { type: "number" },
              FocalPlaneYResolution: { type: "number" },
              MeteringMode: { type: "integer" },
              SceneCaptureType: { type: "integer" },
              LightSource: { type: "integer" },
              SensingMethod: { type: "integer" },
            },
          },
          gps: {
            type: "object",
            properties: {
              GPSLatitude: {
                type: "array",
                items: { type: "number" },
              },
              GPSAltitude: { type: "number" },
              GPSLatitudeRef: { type: "string" },
              GPSSpeed: { type: "number" },
              GPSAltitudeRef: { type: "integer" },
              GPSSpeedRef: { type: "string" },
              GPSLongitudeRef: { type: "string" },
              GPSVersionID: {
                type: "array",
                items: { type: "integer" },
              },
              GPSTimeStamp: {
                type: "array",
                items: { type: "number" },
              },
              GPSDateStamp: { type: "string" },
              GPSLongitude: {
                type: "array",
                items: { type: "number" },
              },
              GPSMapDatum: { type: "string" },
            },
          },
        },
        required: ["bigEndian", "image", "exif", "gps"],
      },
    },
    required: ["fileName", "exifData"],
  },
};
